### ISSUE TITLE
Block comments

### ISSUE THREAD

**Issue by jayphelps** [moonbitlang/moonbit-RFCs#3]
Plans to add block comments? I can make an RFC if necessary, but pretty straight forward: `/* ... */` and allowing them to be nested without limit.

**Comment by hackwaly** [comment]
We are likely to avoid implementing multiline block comments, as they could complicate aspects such as parser recovery and pretty printing. However, we are open to limiting /* ... */ to single-line usage to accommodate certain requirements.

**Comment by jayphelps** [comment]
I think usability table stakes should trump those concerns, but obviously ultimately your call.
